apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tetris-dev
namePrefix: dev-

resources:
- ../../base

patches:
- path: deployment.yaml
- path: service.yaml

labels:
- pairs:
    environment: dev
