apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: tetris
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
