apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: chavo/tetris-arm:v1
        ports:
        - containerPort: 3000
